spring:
  jpa:
    hibernate:
      ddl-auto:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000
    open-in-view: false
    show-sql: true


  datasource:
    url: jdbc:mysql://127.0.0.1:3306/${DATA_BASE}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${USERNAME}
    password: ${PASSWORD}

server:
  port: 8081

